# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perlwikipedia
version:      1.3.0
version_from: lib/Perlwikipedia.pm
installdirs:  site
requires:
    Carp:                          0
    HTML::Entities:                1.35
    URI::Escape:                   3.28
    WWW::Mechanize:                1.30
    XML::Simple:                   2.16

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
